version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: bookstore-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=bookstore

  # Backend service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookstore-backend
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/bookstore
      - PORT=3001
      - NODE_ENV=production

  # Frontend service
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: bookstore-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongodb_data: 